#DEPLOYMENT (the application)
# A Deployment manages a set of identical Pods.
# It ensures that the desired number of replicas is always running.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---

#SERVICE (network exposure)
# A Service exposes the application inside (and outside) the cluster.
# It provides a stable network endpoint for accessing the Pods.

apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      
  # NodePort exposes the service on each node's IP at a static port
  # In k3d, this allows access from the host machine
  type: NodePort
